Option to mount any buckets into a deployment from the local Minio store
scaleoutsystems/stackn pull request #167
Opened 2020-12-10 09:36 UTC by stefanhellander

## Status

- [X ] Ready
- [ ] Draft
- [ ] Hold

## Description

The user can specify which buckets (arbitrary number) from the Minio instance should be mounted in the deployed container.

## Types of changes

What types of changes does your code introduce to STACKn?

- [ ] Hotfix (fixing a critical bug in production)
- [ ] Bugfix
- [ X] New feature
- [ ] Documentation update

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [ X] This pull request is against **develop** branch (not applicable for hotfixes)
- [ ] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [ ] I have read the [CONTRIBUTING](https://github.com/scaleoutsystems/stackn/blob/master/CONTRIBUTING.md) doc
- [ ] I have included tests to complement my changes
- [ ] I have updated the related documentation (if necessary) 
- [ ] I have updated the release notes (docs/releasenotes.md)
- [ ] I have added a reviewer for this pull request
- [ ] I have added myself as an author for this pull request

## Further comments

Anything else you think we should know before merging your code!

2020-12-14 14:16 UTC, morganekmefjord requested changes

2020-12-14 14:16 UTC, morganekmefjord commented on components/chart-controller/controller/controller.py
> +            # If list, don't escape ,
Maybe some try catch would be good here in case of formatting errors.

2020-12-14 14:16 UTC, morganekmefjord commented on components/studio/deployments/models.py
> +
Same here. Maybe some try catch would be good here in case of formatting errors. Many indexing issues that could go wrong by accident.

2020-12-15 07:46 UTC, stefanhellander commented on components/chart-controller/controller/controller.py
> +            # If list, don't escape ,
Done

2020-12-15 07:46 UTC, stefanhellander commented on components/studio/deployments/models.py
> +
Done

2020-12-15 07:47 UTC, merged